/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import MainClasses.AI;
import MainClasses.Administrator;
import MainClasses.LinkList;
import java.util.concurrent.Semaphore;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AndreScarcia
 */
public class Main_UI extends javax.swing.JFrame {
    private AI procesor;
    private Ganadores_UI ganadoresUI;
    /**
     * Creates new form main_UI
     */
    public Main_UI() {
        initComponents();
        
        LinkList winners = new LinkList();
        LinkList winnersSF = new LinkList();
        LinkList winnersZelda = new LinkList();
        Semaphore mutex = new Semaphore(1);
        ganadoresUI = new Ganadores_UI();
        
        this.procesor = new AI(mutex, winners,winnersSF,winnersZelda, this, ganadoresUI);        
        Administrator admin = new Administrator(procesor, mutex, this);
        
        admin.start();
        this.procesor.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        PanelSF = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColaR_Capcom = new javax.swing.JTextPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cola3_Capcom = new javax.swing.JTextPane();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cola2_Capcom = new javax.swing.JTextPane();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Cola1_Capcom = new javax.swing.JTextPane();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Contador_Capcom = new javax.swing.JLabel();
        Ver_Capcom = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        PanelCPU = new javax.swing.JPanel();
        streetPanel = new javax.swing.JPanel();
        streetIcon = new javax.swing.JLabel();
        zeldaPanel = new javax.swing.JPanel();
        zeldaIcon = new javax.swing.JLabel();
        SetTime = new javax.swing.JButton();
        Personaje_SF = new javax.swing.JLabel();
        Personaje_Zelda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DuracionDiaTxt = new javax.swing.JTextField();
        DamageZelda = new javax.swing.JLabel();
        DamageSF = new javax.swing.JLabel();
        VidaZelda = new javax.swing.JLabel();
        VidaSF = new javax.swing.JLabel();
        TurnSF = new javax.swing.JLabel();
        TurnZelda = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Estado_CPU = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        PanelZelda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ColaR_Nintendo = new javax.swing.JTextPane();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Cola3_Nintendo = new javax.swing.JTextPane();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Cola2_Nintendo = new javax.swing.JTextPane();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Cola1_Nintendo = new javax.swing.JTextPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Contador_Nintendo = new javax.swing.JLabel();
        Ver_Nintendo = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSF.setBackground(new java.awt.Color(1, 53, 120));
        PanelSF.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 202, 8));

        jScrollPane1.setViewportView(ColaR_Capcom);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSF.add(jPanel6);
        jPanel6.setBounds(6, 589, 297, 62);

        jPanel15.setBackground(new java.awt.Color(255, 202, 8));

        jScrollPane2.setViewportView(Cola3_Capcom);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSF.add(jPanel15);
        jPanel15.setBounds(6, 499, 297, 62);

        jPanel16.setBackground(new java.awt.Color(255, 202, 8));

        jScrollPane3.setViewportView(Cola2_Capcom);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSF.add(jPanel16);
        jPanel16.setBounds(6, 407, 297, 62);

        jPanel18.setBackground(new java.awt.Color(255, 202, 8));

        jScrollPane5.setViewportView(Cola1_Capcom);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSF.add(jPanel18);
        jPanel18.setBounds(6, 315, 297, 62);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIFs/Street_Fighter_old_logo (Custom).png"))); // NOI18N
        PanelSF.add(jLabel25);
        jLabel25.setBounds(70, 10, 160, 120);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Andre Scarcia & Sebastian Castillo");
        PanelSF.add(jLabel5);
        jLabel5.setBounds(15, 669, 288, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Colas de personajes");
        PanelSF.add(jLabel6);
        jLabel6.setBounds(6, 259, 209, 26);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cola de Refuerzo");
        PanelSF.add(jLabel11);
        jLabel11.setBounds(6, 567, 116, 18);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cola 3");
        PanelSF.add(jLabel12);
        jLabel12.setBounds(6, 475, 56, 18);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cola 2");
        PanelSF.add(jLabel13);
        jLabel13.setBounds(6, 383, 116, 18);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cola 1");
        PanelSF.add(jLabel14);
        jLabel14.setBounds(6, 291, 116, 18);
        PanelSF.add(jLabel16);
        jLabel16.setBounds(290, 6, 0, 0);

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Contador de Ganadores");
        PanelSF.add(jLabel21);
        jLabel21.setBounds(6, 164, 243, 26);

        Contador_Capcom.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        Contador_Capcom.setForeground(new java.awt.Color(255, 255, 255));
        Contador_Capcom.setText("0");
        PanelSF.add(Contador_Capcom);
        Contador_Capcom.setBounds(6, 196, 152, 52);

        Ver_Capcom.setBackground(new java.awt.Color(255, 204, 0));
        Ver_Capcom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Ver_Capcom.setForeground(new java.awt.Color(255, 255, 255));
        Ver_Capcom.setText("Ver Ganadores");
        Ver_Capcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_CapcomActionPerformed(evt);
            }
        });
        PanelSF.add(Ver_Capcom);
        Ver_Capcom.setBounds(150, 216, 140, 31);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIFs/Japan pixel art gifs - GIFs.gif"))); // NOI18N
        PanelSF.add(jLabel24);
        jLabel24.setBounds(-20, 0, 780, 790);

        jPanel1.add(PanelSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 309, 705));

        PanelCPU.setBackground(new java.awt.Color(153, 153, 153));
        PanelCPU.setLayout(null);

        streetPanel.setBackground(new java.awt.Color(255, 102, 51));

        streetIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ryu.png"))); // NOI18N
        streetIcon.setText("jLabel20");

        javax.swing.GroupLayout streetPanelLayout = new javax.swing.GroupLayout(streetPanel);
        streetPanel.setLayout(streetPanelLayout);
        streetPanelLayout.setHorizontalGroup(
            streetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(streetIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE)
        );
        streetPanelLayout.setVerticalGroup(
            streetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(streetIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        PanelCPU.add(streetPanel);
        streetPanel.setBounds(6, 157, 160, 245);

        zeldaPanel.setBackground(new java.awt.Color(255, 102, 51));
        zeldaPanel.setForeground(new java.awt.Color(255, 102, 51));

        zeldaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Link.png"))); // NOI18N
        zeldaIcon.setText("zeldaIcon");

        javax.swing.GroupLayout zeldaPanelLayout = new javax.swing.GroupLayout(zeldaPanel);
        zeldaPanel.setLayout(zeldaPanelLayout);
        zeldaPanelLayout.setHorizontalGroup(
            zeldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zeldaIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, Short.MAX_VALUE)
        );
        zeldaPanelLayout.setVerticalGroup(
            zeldaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zeldaPanelLayout.createSequentialGroup()
                .addComponent(zeldaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        PanelCPU.add(zeldaPanel);
        zeldaPanel.setBounds(172, 157, 160, 245);

        SetTime.setBackground(new java.awt.Color(255, 102, 0));
        SetTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SetTime.setForeground(new java.awt.Color(255, 255, 255));
        SetTime.setText("Aceptar");
        SetTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetTimeActionPerformed(evt);
            }
        });
        PanelCPU.add(SetTime);
        SetTime.setBounds(100, 660, 130, 30);

        Personaje_SF.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Personaje_SF.setForeground(new java.awt.Color(255, 102, 0));
        Personaje_SF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Personaje_SF.setText("Personaje 1");
        Personaje_SF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelCPU.add(Personaje_SF);
        Personaje_SF.setBounds(10, 410, 160, 21);

        Personaje_Zelda.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Personaje_Zelda.setForeground(new java.awt.Color(255, 102, 0));
        Personaje_Zelda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Personaje_Zelda.setText("Personaje 2");
        PanelCPU.add(Personaje_Zelda);
        Personaje_Zelda.setBounds(170, 410, 160, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Editar la velocidad de la simulacion");
        PanelCPU.add(jLabel3);
        jLabel3.setBounds(10, 570, 300, 30);

        DuracionDiaTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DuracionDiaTxt.setText("1");
        DuracionDiaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracionDiaTxtActionPerformed(evt);
            }
        });
        PanelCPU.add(DuracionDiaTxt);
        DuracionDiaTxt.setBounds(180, 610, 110, 40);

        DamageZelda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DamageZelda.setForeground(new java.awt.Color(255, 102, 0));
        DamageZelda.setText("DamageZ");
        PanelCPU.add(DamageZelda);
        DamageZelda.setBounds(170, 480, 150, 19);

        DamageSF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DamageSF.setForeground(new java.awt.Color(255, 102, 0));
        DamageSF.setText("DamageSF");
        PanelCPU.add(DamageSF);
        DamageSF.setBounds(10, 480, 140, 19);

        VidaZelda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VidaZelda.setForeground(new java.awt.Color(255, 102, 0));
        VidaZelda.setText("VidaZelda");
        PanelCPU.add(VidaZelda);
        VidaZelda.setBounds(170, 510, 150, 19);

        VidaSF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VidaSF.setForeground(new java.awt.Color(255, 102, 0));
        VidaSF.setText("VidaSF");
        PanelCPU.add(VidaSF);
        VidaSF.setBounds(10, 510, 140, 19);

        TurnSF.setBackground(new java.awt.Color(255, 255, 255));
        TurnSF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TurnSF.setForeground(new java.awt.Color(255, 102, 0));
        TurnSF.setText("TurnSF");
        PanelCPU.add(TurnSF);
        TurnSF.setBounds(10, 450, 150, 20);

        TurnZelda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TurnZelda.setForeground(new java.awt.Color(255, 102, 0));
        TurnZelda.setText("TurnZelda");
        PanelCPU.add(TurnZelda);
        TurnZelda.setBounds(170, 450, 160, 20);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Dur Segundos");
        PanelCPU.add(jLabel15);
        jLabel15.setBounds(20, 620, 150, 30);

        Estado_CPU.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Estado_CPU.setForeground(new java.awt.Color(255, 102, 51));
        Estado_CPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estado_CPU.setText("ESTADO CPU");
        PanelCPU.add(Estado_CPU);
        Estado_CPU.setBounds(10, 70, 320, 28);

        jLabel19.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 51));
        jLabel19.setText("CPU");
        PanelCPU.add(jLabel19);
        jLabel19.setBounds(109, 6, 140, 60);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIFs/izk7j4s2tmh71.gif"))); // NOI18N
        PanelCPU.add(jLabel20);
        jLabel20.setBounds(-350, 0, 1050, 1170);

        jPanel1.add(PanelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 6, 338, 705));

        PanelZelda.setBackground(new java.awt.Color(179, 0, 14));
        PanelZelda.setPreferredSize(new java.awt.Dimension(309, 594));
        PanelZelda.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Cola de Refuerzo");
        PanelZelda.add(jLabel2);
        jLabel2.setBounds(6, 568, 116, 18);

        jPanel19.setBackground(new java.awt.Color(153, 0, 0));

        jScrollPane6.setBackground(new java.awt.Color(153, 0, 0));
        jScrollPane6.setViewportView(ColaR_Nintendo);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelZelda.add(jPanel19);
        jPanel19.setBounds(6, 590, 297, 62);

        jPanel20.setBackground(new java.awt.Color(153, 0, 0));
        jPanel20.setForeground(new java.awt.Color(143, 143, 143));

        jScrollPane7.setViewportView(Cola3_Nintendo);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelZelda.add(jPanel20);
        jPanel20.setBounds(6, 500, 297, 62);

        jPanel21.setBackground(new java.awt.Color(153, 0, 0));
        jPanel21.setForeground(new java.awt.Color(143, 143, 143));

        jScrollPane8.setViewportView(Cola2_Nintendo);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelZelda.add(jPanel21);
        jPanel21.setBounds(6, 408, 297, 62);

        jPanel22.setBackground(new java.awt.Color(153, 0, 0));
        jPanel22.setForeground(new java.awt.Color(153, 0, 0));

        jScrollPane9.setViewportView(Cola1_Nintendo);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelZelda.add(jPanel22);
        jPanel22.setBounds(6, 318, 297, 62);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIFs/Zelda_Logo.svg (Custom) (1).png"))); // NOI18N
        PanelZelda.add(jLabel22);
        jLabel22.setBounds(20, 20, 280, 110);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText(" Unimet 2023 - Sistemas Operativos");
        PanelZelda.add(jLabel4);
        jLabel4.setBounds(30, 670, 252, 18);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Contador de Ganadores");
        PanelZelda.add(jLabel7);
        jLabel7.setBounds(6, 173, 243, 26);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Cola 2");
        PanelZelda.add(jLabel8);
        jLabel8.setBounds(6, 384, 116, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Cola 3");
        PanelZelda.add(jLabel9);
        jLabel9.setBounds(6, 476, 56, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Cola 1");
        PanelZelda.add(jLabel10);
        jLabel10.setBounds(6, 295, 116, 18);
        PanelZelda.add(jLabel18);
        jLabel18.setBounds(287, 6, 0, 64);

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 0));
        jLabel17.setText("Colas de personajes");
        PanelZelda.add(jLabel17);
        jLabel17.setBounds(6, 263, 209, 26);

        Contador_Nintendo.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        Contador_Nintendo.setForeground(new java.awt.Color(102, 0, 0));
        Contador_Nintendo.setText("0");
        PanelZelda.add(Contador_Nintendo);
        Contador_Nintendo.setBounds(12, 205, 140, 52);

        Ver_Nintendo.setBackground(new java.awt.Color(153, 0, 0));
        Ver_Nintendo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Ver_Nintendo.setForeground(new java.awt.Color(255, 255, 255));
        Ver_Nintendo.setText("Ver Ganadores");
        Ver_Nintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_NintendoActionPerformed(evt);
            }
        });
        PanelZelda.add(Ver_Nintendo);
        Ver_Nintendo.setBounds(163, 225, 140, 31);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GIFs/nintendo-gifs.gif"))); // NOI18N
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelZelda.add(jLabel23);
        jLabel23.setBounds(-122, -14, 500, 740);

        jPanel1.add(PanelZelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 6, -1, 705));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 717));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DuracionDiaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracionDiaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuracionDiaTxtActionPerformed

    private void SetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetTimeActionPerformed
        // TODO add your handling code here:
    try {
            int dur = Integer.parseInt(this.DuracionDiaTxt.getText());
            if (dur < 0) {
                // Mostrar un mensaje de error si el número es negativo
                JOptionPane.showMessageDialog(this, "Por favor ingrese un número entero no negativo.");
            } else {
                this.procesor.setDur(dur);
            }
        } catch (NumberFormatException e) {
            // Mostrar un mensaje de error si el texto no es un entero
            JOptionPane.showMessageDialog(this, "Por favor ingrese un número entero válido.");
        }

    }//GEN-LAST:event_SetTimeActionPerformed

    private void Ver_NintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_NintendoActionPerformed

        if (Integer.parseInt(this.Contador_Capcom.getText()) == 0 || Integer.parseInt(this.Contador_Nintendo.getText()) == 0){
         JOptionPane.showMessageDialog(this, "No se pueden mostrar las listas porque todavia no hay ganadores");
        }else{
        this.ganadoresUI.setVisible(true);
        this.ganadoresUI.getListSF().setText(this.procesor.winnerListSF.printList());
        this.ganadoresUI.getListZelda().setText(this.procesor.winnerListZelda.printList());
        }
    }//GEN-LAST:event_Ver_NintendoActionPerformed

    private void Ver_CapcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_CapcomActionPerformed
        // TODO add your handling code here:
        
        if (Integer.parseInt(this.Contador_Capcom.getText()) == 0 || Integer.parseInt(this.Contador_Nintendo.getText()) == 0){
         JOptionPane.showMessageDialog(this, "No se pueden mostrar las listas porque todavia no hay ganadores");
        }else{
        this.ganadoresUI.setVisible(true);
        this.ganadoresUI.getListSF().setText(this.procesor.winnerListSF.printList());
        this.ganadoresUI.getListZelda().setText(this.procesor.winnerListZelda.printList());
        }
    }//GEN-LAST:event_Ver_CapcomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_UI().setVisible(true);
            }
        });
    }
    
    public void setTurnZelda(String Zelda) {
        this.TurnZelda.setText(Zelda);

    }

    public void setTurnSF(String SF) {
        this.TurnSF.setText(SF);

    }

    public void setVidaSF(String SF) {
        this.VidaSF.setText(SF);

    }

    public void setDamageSF(String SF) {
        this.DamageSF.setText(SF);
    }

    public void setDamageZelda(String Zelda) {
        this.DamageZelda.setText(Zelda);
    }

    public void setVidaZelda(String Zelda) {
        this.VidaZelda.setText(Zelda);

    }

    public JTextPane getColaR_Capcom() {
        return ColaR_Capcom;
    }

    public JTextPane getCola3_Capcom() {
        return Cola3_Capcom;
    }

    public JTextPane getCola2_Capcom() {
        return Cola2_Capcom;
    }

    public JTextPane getCola1_Capcom() {
        return Cola1_Capcom;
    }

    public JTextPane getColaR_Nintendo() {
        return ColaR_Nintendo;
    }

    public JTextPane getCola3_Nintendo() {
        return Cola3_Nintendo;
    }

    public JTextPane getCola2_Nintendo() {
        return Cola2_Nintendo;
    }

    public JTextPane getCola1_Nintendo() {
        return Cola1_Nintendo;
    }
    
    public JLabel getstreetIcon(){
        return streetIcon;
    }
    
    public JLabel getzeldaIcon(){
        return zeldaIcon;
    }
    
    public JLabel getStreetWin(){
        return Contador_Capcom;
    }
    
    public JLabel getZeldaWin(){
        return Contador_Nintendo;
    }
    public JLabel getEstadoCPU() {
        return Estado_CPU;
    }
    
    public JLabel getPersonajeSFLabel() {
        return Personaje_SF; 
    }

    public void setPersonajeSFLabel(String text) {
        Personaje_SF.setText(text);
    }

    public JLabel getPersonajeZeldaLabel() {
        return Personaje_Zelda; 
    }

    public void setPersonajeZeldaLabel(String text) {
        Personaje_Zelda.setText(text);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Cola1_Capcom;
    private javax.swing.JTextPane Cola1_Nintendo;
    private javax.swing.JTextPane Cola2_Capcom;
    private javax.swing.JTextPane Cola2_Nintendo;
    private javax.swing.JTextPane Cola3_Capcom;
    private javax.swing.JTextPane Cola3_Nintendo;
    private javax.swing.JTextPane ColaR_Capcom;
    private javax.swing.JTextPane ColaR_Nintendo;
    private javax.swing.JLabel Contador_Capcom;
    private javax.swing.JLabel Contador_Nintendo;
    private javax.swing.JLabel DamageSF;
    private javax.swing.JLabel DamageZelda;
    private javax.swing.JTextField DuracionDiaTxt;
    private javax.swing.JLabel Estado_CPU;
    private javax.swing.JPanel PanelCPU;
    private javax.swing.JPanel PanelSF;
    private javax.swing.JPanel PanelZelda;
    private javax.swing.JLabel Personaje_SF;
    private javax.swing.JLabel Personaje_Zelda;
    private javax.swing.JButton SetTime;
    private javax.swing.JLabel TurnSF;
    private javax.swing.JLabel TurnZelda;
    private javax.swing.JButton Ver_Capcom;
    private javax.swing.JButton Ver_Nintendo;
    private javax.swing.JLabel VidaSF;
    private javax.swing.JLabel VidaZelda;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel streetIcon;
    private javax.swing.JPanel streetPanel;
    private javax.swing.JLabel zeldaIcon;
    private javax.swing.JPanel zeldaPanel;
    // End of variables declaration//GEN-END:variables
}
